# Generated by Django 4.2.7 on 2025-09-08 21:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('transaction_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=10, verbose_name='Tipo de Transacción')),
                ('category', models.CharField(choices=[('salary', 'Salario'), ('freelance', 'Trabajo Independiente'), ('investment', 'Inversiones'), ('gift', 'Regalo'), ('other_income', 'Otros Ingresos'), ('food', 'Alimentación'), ('transport', 'Transporte'), ('utilities', 'Servicios Públicos'), ('entertainment', 'Entretenimiento'), ('healthcare', 'Salud'), ('education', 'Educación'), ('shopping', 'Compras'), ('rent', 'Arriendo'), ('other_expense', 'Otros Gastos')], max_length=20, verbose_name='Categoría')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
